Controllers:
  - Id: 0
    ConrtollerType: DualShock
    Modifier:
    Mapping:
      - !DualShock
        Inputs:
          Stick: LeftStick
        Output: LeftStick
        Converter: StickToStickConverter
      - !DualShock
        Inputs:
          Trigger: LeftTrigger
        Output: LeftTrigger
        Converter: TriggerToTriggerConverter
      - !DualShock
        Inputs:
          Button: LeftTriggerButton
        Output: LeftTriggerButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: LeftStickButton
        Output: LeftStickButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Stick: RightStick
        Output: RightStick
        Converter: StickToStickConverter
      - !DualShock
        Inputs:
          Trigger: RightTrigger
        Output: RightTrigger
        Converter: TriggerToTriggerConverter
      - !DualShock
        Inputs:
          Button: RightTriggerButton
        Output: RightTriggerButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: RightStickButton
        Output: RightStickButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: TriangleButton
        Output: TriangleButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: CircleButton
        Output: CircleButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: CrossButton
        Output: CrossButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: SquareButton
        Output: SquareButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadNorth
        Output: DPadNorth
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadNorthEast
        Output: DPadNorthEast
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadEast
        Output: DPadEast
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadSouthEast
        Output: DPadSouthEast
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadSouth
        Output: DPadSouth
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadSouthWest
        Output: DPadSouthWest
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadWest
        Output: DPadWest
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadNorthWest
        Output: DPadNorthWest
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadNone
        Output: DPadNone
        Converter: ButtonToButtonConverter
  - Id: 1
    ConrtollerType: DualShock
    Modifier:
      - LeftShoulder
    Mapping:
      - !DualShock
        Global: true
        Inputs:
          Accelerometer: Accelerometer
          Gyro: Gyro
          Stick: RightStick
          Zero: TouchButton
          Toggle: CreateButton
        Output: RightStick
        Converter: TiltAndStickToStickConverter
        Arguments:
          AlphaX: 1,0
          AlphaY: 1,0
          BetaX: 1,0
          BetaY: 1,0
          Sensitivity: 1,7
          Deadzone: 0,1
      - !DualShock
        Inputs:
          Stick: LeftStick
        Output: LeftStick
        Converter: StickToStickConverter
      - !DualShock
        Inputs:
          Trigger: LeftTrigger
        Output: LeftTrigger
        Converter: TriggerToTriggerConverter
      - !DualShock
        Inputs:
          Button: LeftTriggerButton
        Output: LeftTriggerButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: LeftStickButton
        Output: LeftStickButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Trigger: RightTrigger
        Output: RightTrigger
        Converter: TriggerToTriggerConverter
      - !DualShock
        Inputs:
          Button: RightTriggerButton
        Output: RightTriggerButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: RightStickButton
        Output: RightStickButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: TriangleButton
        Output: TriangleButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: CircleButton
        Output: CircleButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: CrossButton
        Output: CrossButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: SquareButton
        Output: SquareButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadNorth
        Output: DPadNorth
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadNorthEast
        Output: DPadNorthEast
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadEast
        Output: DPadEast
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadSouthEast
        Output: DPadSouthEast
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadSouth
        Output: DPadSouth
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadSouthWest
        Output: DPadSouthWest
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadWest
        Output: DPadWest
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadNorthWest
        Output: DPadNorthWest
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadNone
        Output: DPadNone
        Converter: ButtonToButtonConverter  
  - Id: 2
    ConrtollerType: DualShock
    Modifier:
      - RightShoulder
    Mapping:
      - !DualShock
        Global: true
        Inputs:
          Gyro: Gyro
          Stick: RightStick
          Toggle: MenuButton
        Output: RightStick
        Converter: GyroAndStickToStickConverter
        Arguments:
          AlphaX: 1,0
          AlphaY: 1,0
          BetaX: 1,0
          BetaY: 1,0
          GammaX: 0,9
          GammaY: 0,9
          EpsilonX: 0,05
          EpsilonY: 0,05
      - !DualShock
        Inputs:
          Stick: LeftStick
        Output: LeftStick
        Converter: StickToStickConverter
      - !DualShock
        Inputs:
          Trigger: LeftTrigger
        Output: LeftTrigger
        Converter: TriggerToTriggerConverter
      - !DualShock
        Inputs:
          Button: LeftTriggerButton
        Output: LeftTriggerButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: LeftStickButton
        Output: LeftStickButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Trigger: RightTrigger
        Output: RightTrigger
        Converter: TriggerToTriggerConverter
      - !DualShock
        Inputs:
          Button: RightTriggerButton
        Output: RightTriggerButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: RightStickButton
        Output: RightStickButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: TriangleButton
        Output: TriangleButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: CircleButton
        Output: CircleButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: CrossButton
        Output: CrossButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: SquareButton
        Output: SquareButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadNorth
        Output: DPadNorth
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadNorthEast
        Output: DPadNorthEast
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadEast
        Output: DPadEast
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadSouthEast
        Output: DPadSouthEast
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadSouth
        Output: DPadSouth
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadSouthWest
        Output: DPadSouthWest
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadWest
        Output: DPadWest
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadNorthWest
        Output: DPadNorthWest
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          Button: DPadNone
        Output: DPadNone
        Converter: ButtonToButtonConverter
