Controllers:
  - Id: 0
    ConrtollerType: DualShock
    Modifier:
    Mapping:
      - !DualShock
        Output: LeftStick
        Input: LeftStick
        ConverterArguments:
  - Id: 1
    ConrtollerType: XBox360
    Modifier:
      - LeftShoulder
    Mapping:
      - !XBox360
        Output: YButton
        Input: TriangleButton
        Converter: ButtonToButtonConverter
        ConverterArguments:
      - !XBox360
        Global: true
        Output: LeftStick
        Input: Tilt
        Converter: TiltToStickConverter
        InputArguments:
          - TouchButton
          - MicButton
        ConverterArguments:
          - 1,5 
          - 0,2