Controllers:
  - Id: 0
    ConrtollerType: DualShock
    Modifier:
    Mapping:
      - !DualShock
        Output: CircleButton
        Input: CircleButton
        Converter: ButtonToButtonConverter
        ConverterArguments:
      - !DualShock
        Output: CrossButton
        Input: SquareButton
        Converter: ButtonToButtonConverter
        ConverterArguments: 
  - Id: 1
    ConrtollerType: XBox360
    Modifier:
      - LeftShoulder
    Mapping:
      - !XBox360
        Output: XButton
        Input: CircleButton
        Converter: ButtonToButtonConverter
        ConverterArguments:
      - !XBox360
        Output: AButton
        Input: SquareButton
        Converter: ButtonToButtonConverter
        ConverterArguments: 