Controllers:
  - Id: 0
    ConrtollerType: DualShock
    Modifier:
    Mapping:
      - !DualShock
        Inputs:
          - LeftStick
        Output: LeftStick
        Converter: StickToStickConverter
      - !DualShock
        Inputs:
          - LeftTrigger
        Output: LeftTrigger
        Converter: TriggerToTriggerConverter
      - !DualShock
        Inputs:
          - LeftStickButton
        Output: LeftStickButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          - RightStick
        Output: RightStick
        Converter: StickToStickConverter
      - !DualShock
        Inputs:
          - RightTrigger
        Output: RightTrigger
        Converter: TriggerToTriggerConverter
      - !DualShock
        Inputs:
          - RightStickButton
        Output: RightStickButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          - TriangleButton
        Output: TriangleButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          - CircleButton
        Output: CircleButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          - CrossButton
        Output: CrossButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          - SquareButton
        Output: SquareButton
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          - DPadNorth
        Output: DPadNorth
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          - DPadNorthEast
        Output: DPadNorthEast
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          - DPadEast
        Output: DPadEast
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          - DPadSouthEast
        Output: DPadSouthEast
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          - DPadSouth
        Output: DPadSouth
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          - DPadSouthWest
        Output: DPadSouthWest
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          - DPadWest
        Output: DPadWest
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          - DPadNorthWest
        Output: DPadNorthWest
        Converter: ButtonToButtonConverter
      - !DualShock
        Inputs:
          - DPadNone
        Output: DPadNone
        Converter: ButtonToButtonConverter
  - Id: 1
    ConrtollerType: DualShock
    Modifier:
      - LeftShoulder
    Mapping:
      - !DualShock
        Global: true
        Inputs:
          - Tilt
          - RightStick
          - TouchButton
          - MicButton
        Output: RightStick
        Converter: TiltAndStickToStickConverter
        ConverterArguments:
          AlphaX: 1,0
          AlphaY: 1,0
          BetaX: 1,0
          BetaY: 1,0
          Sensitivity: 1,7
          Deadzone: 0,1
  - Id: 2
    ConrtollerType: DualShock
    Modifier:
      - LeftShoulder
    Mapping:
      - !DualShock
        Global: true
        Inputs:
          - Tilt
          - RightStick
          - MicButton
        Output: RightStick
        Converter: GyroAndStickToStickConverter
        ConverterArguments:
          AlphaX: 1,0
          AlphaY: 1,0
          BetaX: 1,0
          BetaY: 1,0
          GammaX: 0,05
          GammaY: 0,05
