Controllers:
  - Id: 0
    ConrtollerType: XBox360
    Modifier:
    Mapping:
      - !XBox360
        Output: YButton
        Input: TriangleButton
        Converter: ButtonToButtonConverter
        ConverterArguments:
  - Id: 1
    ConrtollerType: DualShock
    Modifier:
      - LeftShoulder
    Mapping:
      - !DualShock
        Output: CircleButton
        Input: CircleButton
        Converter: ButtonToButtonConverter
        ConverterArguments: